"""create teacher assignments

Revision ID: 6cdadd3a3692
Revises: 9402a3280340
Create Date: 2026-09-26 12:06:29.330505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cdadd3a3692'
down_revision: Union[str, Sequence[str], None] = '9402a3280340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_profile_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['teacher_profile_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_profile_id', 'section_id', name='uq_teacher_section')
    )
    op.create_index(op.f('ix_teacher_assignments_id'), 'teacher_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_section_id'), 'teacher_assignments', ['section_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_teacher_profile_id'), 'teacher_assignments', ['teacher_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_assignments_teacher_profile_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_section_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_id'), table_name='teacher_assignments')
    op.drop_table('teacher_assignments')
    # ### end Alembic commands ###
