from app.models.user import User
from app.models.role import Role
from app.models.user_role import UserRole
from app.models.person import Person
from app.models.student_profile import StudentProfile
from app.models.teacher_profile import TeacherProfile
from app.models.staff_profile import StaffProfile
from app.models.department import Department
from app.models.program import Program
from app.models.course import Course
from app.models.section import Section
from app.models.enrollment import Enrollment
from app.models.teacher_assignment import TeacherAssignment